{% set name = "Markdown" %}
{% set version = "3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: "5ad7180c3ec16422a764568ad6409ec82460c40d1631591fa53d597033cc98bf"

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - markdown_py = markdown.__main__:run

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - setuptools >=36

test:
  imports:
    - markdown
    - markdown.extensions
  commands:
    - markdown_py -h

about:
  home: https://python-markdown.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Python implementation of Markdown.'
  description: |
    This is a Python implementation of John Gruber’s Markdown. It is almost
    completely compliant with the reference implementation, though there are a
    few known issues.
  doc_url: https://python-markdown.github.io/
  dev_url: https://github.com/Python-Markdown/markdown

extra:
  recipe-maintainers:
    - dougalsutherland
    - philip-khor
