{% set name = "Markdown" %}
{% set version = "3.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 76df8ae32294ec39dcf89340382882dfa12975f87f45c3ed1ecdb1e8cefc7006

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - markdown_py = markdown.__main__:run

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - importlib-metadata >=4.4
    - python >=3.6

test:
  imports:
    - markdown
    - markdown.extensions
  commands:
    - markdown_py -h

about:
  home: https://python-markdown.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Python implementation of Markdown.
  description: |
    This is a Python implementation of John Gruber’s Markdown. It is almost
    completely compliant with the reference implementation, though there are a
    few known issues.
  doc_url: https://python-markdown.github.io/
  dev_url: https://github.com/Python-Markdown/markdown

extra:
  recipe-maintainers:
    - djsutherland
    - philip-khor
