{% set name = "Markdown" %}
{% set version = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: 37062d4f2aa4b2b6b32aefb80faa300f82cc790cb949a35b8caede34f2b68c0e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - markdown_py = markdown.__main__:run

requirements:
  host:
    - setuptools >=77.0
    - pip
    - python {{ python_min }}
  run:
    - importlib-metadata >=4.4
    - python >={{ python_min }}

test:
  imports:
    - markdown
    - markdown.extensions
  commands:
    - markdown_py -h
  requires:
    - python {{ python_min }}

about:
  home: https://python-markdown.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Python implementation of Markdown.
  description: |
    This is a Python implementation of John Gruber’s Markdown. It is almost
    completely compliant with the reference implementation, though there are a
    few known issues.
  doc_url: https://python-markdown.github.io/
  dev_url: https://github.com/Python-Markdown/markdown

extra:
  recipe-maintainers:
    - djsutherland
    - philip-khor
