schema_version: 1

context:
  name: Markdown
  version: "3.10.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | lower }}-${{ version }}.tar.gz
  sha256: 994d51325d25ad8aa7ce4ebaec003febcce822c3f8c911e3b17c52f7f589f950

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv
  python:
    entry_points:
      - markdown_py = markdown.__main__:run

requirements:
  host:
    - setuptools >=77.0
    - pip
    - python ${{ python_min }}.*
  run:
    - importlib-metadata >=4.4
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - markdown
        - markdown.extensions
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - markdown_py -h

about:
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: Python implementation of Markdown.
  description: |
    This is a Python implementation of John Gruber’s Markdown. It is almost
    completely compliant with the reference implementation, though there are a
    few known issues.
  homepage: https://python-markdown.github.io/
  repository: https://github.com/Python-Markdown/markdown
  documentation: https://python-markdown.github.io/

extra:
  recipe-maintainers:
    - djsutherland
    - philip-khor
